name: cdc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: 1.1.0
  shared_preferences: 2.2.2
  get: 4.6.6
  google_fonts: 6.1.0
  smooth_page_indicator: 1.1.0
  firebase_auth: 4.12.1
  pinput: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

